version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - pai-sql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pai-trello
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pai-sql:
