default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_trello_dev

test:
  <<: *default
  database: pai_trello_test

production:
  <<: *default
  username: <%= ENV['PAI_TRELLO_USERNAME'] %>
  password: <%= ENV['PAI_TRELLO_PASSWORD'] %>
  host: <%= ENV['PAI_TRELLO_HOST'] %>
  database: <%= ENV['PAI_TRELLO_DATABASE_'] %>
